// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLatestClipboard() {
  return window['go']['main']['App']['GetLatestClipboard']();
}

export function GetLatestScreenshot() {
  return window['go']['main']['App']['GetLatestScreenshot']();
}
