// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLatestClipboard():Promise<main.ClipboardResponse>;

export function GetLatestScreenshot():Promise<string>;
